version: '3.9'
services:

  nginx:
    container_name: nginx
    image: nginx:1.23.0
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/public:/usr/share/nginx/html:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites
    environment:
      TZ: Asia/Tokyo
    restart: always
    networks:
      - internal
      - images_default
      - videos_default

  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: always
    command: tunnel --no-chunked-encoding --config $HOME/.cloudflared/www.yml run www
    volumes:
      - '$HOME/.cloudflared:/root/.cloudflared'
    depends_on:
      - nginx
    networks:
      - internal

networks:
  internal:
  images_default:
    external: true
  videos_default:
    external: true